### ISSUE TITLE
Why do you plan to replace ffplayout with ffplayout-engine?

### ISSUE THREAD

**Issue by computersrmyfriends** [ffplayout/ffplayout-engine#1]
Hi,

Thanks for your great work.

I would like to know why you are planning to replace ffplayout with ffplayout-engine which uses pyAV?

Isn't pyAV more complicated than using standard ffmpeg commandline? Wouldn't that be more straightforward? The ffplayout is more simpler to read and understand how it works than the ffplayout-engine.

Also,are there any new features added in the ffplayout-engine?

Thanks

**Comment by jb-alvarado** [comment]
Hi, you are wellcome!
At the moment I'm fare away from replacing ffplayout, first I have to understand pyAV better.

Yes ffplayout is more easy to understand but it have some things I don't like:
- it needs 2 encoding processes
- it is not really posible to calculate that if we are snyc with the real time
- after some Hours we run a Bit out of sync 
- we need a external buffer 
- we run ffplayout 24/7 and for this it could be a bit more stable 
- the code from ffplayout is in some parts a Bit messy 

I hope that this things I can fix with ffplayout-engine.

**Comment by computersrmyfriends** [comment]
Hi,
Thank you for explaining.

Have you also considered moviepy,MLT framework,Vidpy,etc?

I feel the ffplayout code very easy to read and understand and it's much easier to maintain,solve bugs and have control but I can also see the advantage of pyAV. I think it directly uses ffmpeg library to handle the details instead of the executable right?

What is on your roadmap for ffplayout now? 

Thanks

**Comment by jb-alvarado** [comment]
I looked on moviepy, but it is mutch more code to handle and for a playout solution it was not so usefull to me. mlt is a interessting project to, but you need to Write around your own xml parser and I have no cloue of how to feed mlt contiuesly with clips and have dynamical playlists. 

I beleave when ffplayout-engine becomes production ready it will ne good readeble to! All the higher magic makes pyAV and we don't have to worry about it. And yes pyAV works directly with the ffmpeg libs. 

ffplayout have a project page, there you see some ideas, but because I can not fix some issues I have listed on top, I'm not sure of how much energy I will put on on. Of course I will fix bugs, and when other people want to help, that is wellcome to!
