### ISSUE TITLE
a fall back video

### ISSUE THREAD

**Issue by maddigibiter** [ffplayout/ffplayout-engine#18]
Hi a quick question that I needed to ask and Config guide kind of lost me there. If a playlist is less than 24 hours, I'd like to have a back up video to fill up rest of the remaining time. As an example my start time is 00:00 and end of day is 24:00, I have a playlist that has 23 hrs duration, would it be possible to have a video to play instead of gen_dummy() function? Would it be possible to return a video file instead to stream? Is there anyway to achieve that in current configuration?

Thanks

**Comment by maddigibiter** [comment]
Just going back to documentation, I've add a dummy clip and path is correct based on this part of description "trim and fade the last clip, to get full 24 hours, if the duration is less then 6 seconds add a dummy clip". 

Is there any reason why less than 6 seconds? I'm sure there is a rational behind this just don't understand  it. 

Thanks

**Comment by jb-alvarado** [comment]
Hi, sorry that the explanations a confusing.

To your first question:
I think I can implement this, I only need a good way what covers all scenarios. At the moment `filler_clip`is for the Web GUI only, I can change this, but then I need an extra options which says use this clip or fill with black.
But do you want to use a clip which is longer then an hour, or do you want a clip which loops until the 24 hours a riches?  The first case is easier. You have need to know that the last clip will cut at the begin, when is to long, not at the end. This I don't want to change, because in our workflow we use a animated clock, which count to zero and here it is nicer when the begin is cut away not the end.

A fast way for the moment is, that you just put your filler clip to the playlist.

To your second question:
The 6 seconds I just choose because I though it is better for the spectator to have 6 seconds black, then a short video what is sliced with no meaning.

Stream copy means that there is no recompression, ffmpeg will run with `-c copy`. This scenario works only when all clips compressed the same way with x264 or mpeg2. Also `blackclip` has to be compressed in the same way. But I'm not recommend this for longer runs.

**Comment by maddigibiter** [comment]
Thanks for quick response as usual. On demand streams never can be 100%, from big or small broadcasting services you can always see there is a gap to fill in. Answering your questions, ideally a fallback video that can loop in order to fill that gap, you can see examples from CNN or other broadcasting streams minutes before their reach their local end of day.  

As you mentioned to add filter clip to playlist, isn't this the same? 

Thanks for clarifying other 2 questions about stream copy and 6 seconds. 

Br

**Comment by jb-alvarado** [comment]
Something like this: [BBC filler](https://www.youtube.com/watch?v=rVYgsCclWJs)
I could try to implement this, but maybe it takes a bit time. 
The loop can be realize with ffmpeg to, i guess. For this I have to calculate to length and check how many times to the clips length fits in the gap.

**Comment by jb-alvarado** [comment]
In master branch is now a version which support this feature. 
Is not much tested, so I can not guarantee that it is production ready.

**Comment by maddigibiter** [comment]
Wow, thanks for update. Its working on my side, I let it play for few hours and let you know.

Thank you
