### ISSUE TITLE
hardware decoding/encoding

### ISSUE THREAD

**Issue by jb-alvarado** [ffplayout/ffplayout-engine#33]
This question I got ask by email, but I think it could be interessting for others to.

The question was how to integrate hw decoding/encoding in ffplayout.

Please give me some working ffmpeg examples - then I can answer this question better and also think about if it is possible to integrate it in ffplayout directly.

**Comment by jb-alvarado** [comment]
I close here for now. When is necessary, we can open a new issue for that topic.

**Comment by d21d3q** [comment]
> Sidenote: I was playing around with generating live videos, and your repository was very helpful so thank you for your effort!

I think I can have some suggestion here. It is not about hardware decoding/encoding, but a way of offloading your cpu.

So if you don't need any dynamic overlay, videos can be transcoded in advanca and then piped to rtmp server. I did something like this:
```bash
#!/bin/bash

ffmpeg              \
  -y                \
  -an               \
  -i $1             \
  -c:v libx264      \
  -preset ultrafast \
  -b:v 50M          \
  -maxrate 50M      \
  -minrate 50M      \
  -f mpegts         \
  "$(echo $1 | cut -f1 -d '.').flv"
```
and then args for ffmpeg: 
```
    ffmpegArgs := []string{
        "-re",
        "-i", "pipe:0",
        "-c", "copy",
        "-f", "flv",
        conf.RtmpServer, channel.Id
```
and then for playing you don't need ffmpeg, you can copy files directly to pipe.  
your cpu won't even notice that something is going on.

If suppose that adding dynamic overlay to pre-transcoded video could be also less resource intensive as live transcoding.

**Comment by jb-alvarado** [comment]
Hello,
thank you for your suggestion! In the past I had a copy mode in the script, which allowed this behaviour. But to me it is a bit to unstable. All the file needs to have exactly the same settings. And to have this in mind over years with thousands of file is difficult. 
But for smaller settings it could be convenient - when there is a need I could put it on my TODO.

Another way to use less resources could be to, to write directly to an hls .m3u8 playlist, This would skipt the pre-compression step.

**Comment by d21d3q** [comment]
> And to have this in mind over years with thousands of file is difficult.

no doubts about it.  

I went the road of `dash`/`hls`. My requirement was to play video with `ffplay` so I was testing against it.  
With `dash` this should be achieved by producing dynamic list of [periods](https://dashif-documents.azurewebsites.net/Guidelines-TimingModel/master/Guidelines-TimingModel.html#period-timing) but ffplay doesn't seem to support multiple periods, while playing with [reference player](https://github.com/Dash-Industry-Forum/dash.js) seemd to work fine.  
With live `hls`, ffplay was refreshing playlist (and downloading new videos) after it has been done with playing videos from previous refresh, so that there was a lag between videos (even when playing on same machine that is serving).

But for playing from browser it should be good solution.

**Comment by jb-alvarado** [comment]
Do you know [python-mpv](https://github.com/jaseg/python-mpv)? This is a interesting project to, because you can also feed the player with a playlist. When you need desktop playback, this could be a good solution to.

**Comment by cdavid14** [comment]
i think that the topic hw decoding/encoding its about nvidia GPU instead of GPU Decoding/Encoding, an example about how use full GPU solution with ffmpeg arguments:
```

ffmpeg \
   -hwaccel cuda \ <-- says to ffmpeg that you will use cuda for hardware acceleration
   -c:v h264_cuvid \ <-- says that you will use h264 nvidia decoder (hardware) instead of any other software decoder, could be mpeg2_cuvid for mpeg2 decoder too
   -i pipe:0 \
   -c:v h264_nvenc \ <-- now here we set the video encoder with nvidia encoder (hardware)
   -f null - 
```

this will use the GPU for decode and encode and send the pipeline already processed to the CPU like this
![image](https://user-images.githubusercontent.com/5961014/90327744-36150d00-df6d-11ea-83a2-47c8b3431525.png)

if you don`t use the hwaccel option and use the encoder and decoder from nvidia the processing will also use the GPU, but sharing system memory, like the image above illustrate (that could be great for h264 10bit decoding/encoding)
![image](https://user-images.githubusercontent.com/5961014/90327763-6ceb2300-df6d-11ea-8093-2fc6b5be7714.png)

Nvidia has also their own filters that are equivalent to the ffmpeg original filters, but using GPU to process, like scale_npp or yadif_cuda..

i think that a playout machine with a GPU powered solution integrated with ffplayout it's alot interesting for some people.. I've talked about Nvidia because it's more common around video processing but you can do it with AMD GPUs also using VAAPI

**Comment by jb-alvarado** [comment]
Thank you for your detailed explanation! I think I could integrate a generic input option, where everybody can write his own ffmpeg input commands. The problem is a bit, that for the streaming mode I use two ffmpeg instances and I guess both needs different input options. So I have to think about how is the best way, so that user don't get confuse. HW filtering is a bit more complicate to have a generic way.

**Comment by jb-alvarado** [comment]
For this task I don't found time at the moment and I have not the hardware for it. PRs are welcome.
