### ISSUE TITLE
Failed to start python and ffmpeg based playout

### ISSUE THREAD

**Issue by awlakha** [ffplayout/ffplayout-engine#62]
Hi,
I face an issue on ffplayout engine. It shows error on starting the service. "Failed to start python and ffmpeg based playout"

ffplayout-engine.service - python and ffmpeg based playout
   Loaded: loaded (/etc/systemd/system/ffplayout-engine.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-07-30 15:16:35 UTC; 3s ago
  Process: 3033 ExecStart=/opt/ffplayout-engine/venv/bin/python /opt/ffplayout-engine/ffplayout.py (code=exited, status=1/FAILURE)
 Main PID: 3033 (code=exited, status=1/FAILURE)
Jul 30 15:16:34 ffplayout-1 systemd[1]: ffplayout-engine.service: Main process exited, code=exited, status=1/FAILURE
Jul 30 15:16:34 ffplayout-1 systemd[1]: ffplayout-engine.service: Failed with result 'exit-code'.
Jul 30 15:16:35 ffplayout-1 systemd[1]: ffplayout-engine.service: Service RestartSec=1s expired, scheduling restart.
Jul 30 15:16:35 ffplayout-1 systemd[1]: ffplayout-engine.service: Scheduled restart job, restart counter is at 5.
Jul 30 15:16:35 ffplayout-1 systemd[1]: Stopped python and ffmpeg based playout.
Jul 30 15:16:35 ffplayout-1 systemd[1]: ffplayout-engine.service: Start request repeated too quickly.
Jul 30 15:16:35 ffplayout-1 systemd[1]: ffplayout-engine.service: Failed with result 'exit-code'.
Jul 30 15:16:35 ffplayout-1 systemd[1]: Failed to start python and ffmpeg based playout.

**Comment by jb-alvarado** [comment]
Hi, can you start it by hand?, with:

```
/opt/ffplayout-engine/venv/bin/python /opt/ffplayout-engine/ffplayout.py
´´´
Somewhere, in output or in one of the logs, it should say what is happen.

**Comment by techvi8** [comment]
Hey,

I am also facing the same ffplayout-engine daemon failure issue. Below are the logs-:

root@ubuntu:~/playlists/2020/09# /opt/ffplayout-engine/venv/bin/python /opt/ffplayout-engine/ffplayout.py
Traceback (most recent call last):
  File "/opt/ffplayout-engine/ffplayout.py", line 64, in <module>
    main()
  File "/opt/ffplayout-engine/ffplayout.py", line 58, in main
    output()
  File "/opt/ffplayout-engine/ffplayout/output/stream.py", line 64, in output
    watcher = MediaWatcher(media)
  File "/opt/ffplayout-engine/ffplayout/folder.py", line 98, in __init__
    self.observer.start()
  File "/opt/ffplayout-engine/venv/lib/python3.8/site-packages/watchdog/observers/api.py", line 260, in start
    emitter.start()
  File "/opt/ffplayout-engine/venv/lib/python3.8/site-packages/watchdog/utils/__init__.py", line 110, in start
    self.on_thread_start()
  File "/opt/ffplayout-engine/venv/lib/python3.8/site-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/opt/ffplayout-engine/venv/lib/python3.8/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/opt/ffplayout-engine/venv/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 203, in __init__
    self._add_watch(path, event_mask)
  File "/opt/ffplayout-engine/venv/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 412, in _add_watch
    Inotify._raise_error()
  File "/opt/ffplayout-engine/venv/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 432, in _raise_error
    raise OSError(err, os.strerror(err))
FileNotFoundError: [Errno 2] No such file or directory
 
Please help.

Thanks

**Comment by jb-alvarado** [comment]
Hi, have you set the correct path to your media files, in the config? The message says that there is a file which is not found.

**Comment by navneetpal-git** [comment]
Hello,

I am facing the same issue when I hit the below command getting the errors

:/opt/ffplayout_engine# sudo systemctl status ffplayout_engine
● ffplayout_engine.service - python and ffmpeg based playout
   Loaded: loaded (/etc/systemd/system/ffplayout_engine.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2022-03-08 16:01:13 UTC; 320ms ago
  Process: 15542 ExecStart=/opt/ffplayout_engine/venv/bin/python /opt/ffplayout_engine/ffplayout.py (code=exited, status=1/FAILURE)
 Main PID: 15542 (code=exited, status=1/FAILURE)

Mar 08 16:01:13 ip- systemd[1]: ffplayout_engine.service: Service hold-off time over, scheduling restart.
Mar 08 16:01:13 ip- systemd[1]: ffplayout_engine.service: Scheduled restart job, restart counter is at 5.
Mar 08 16:01:13 ip- systemd[1]: Stopped python and ffmpeg based playout.
Mar 08 16:01:13 ip- systemd[1]: ffplayout_engine.service: Start request repeated too quickly.
Mar 08 16:01:13 ip- systemd[1]: ffplayout_engine.service: Failed with result 'exit-code'.
Mar 08 16:01:13 ip- systemd[1]: Failed to start python and ffmpeg based playout.


As you suggested above to hit this command  /opt/ffplayout-engine/venv/bin/python /opt/ffplayout-engine/ffplayout.py getting the errors

/opt/ffplayout_engine# /opt/ffplayout_engine/venv/bin/python /opt/ffplayout_engine/ffplayout.py
Traceback (most recent call last):
  File "/opt/ffplayout_engine/ffplayout/output/stream.py", line 71, in output
    messenger.debug(f'Encoder CMD: "{" ".join(enc_cmd)}"')
TypeError: sequence item 13: expected str instance, int found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ffplayout_engine/ffplayout.py", line 67, in <module>
    main()
  File "/opt/ffplayout_engine/ffplayout.py", line 58, in main
    output()
  File "/opt/ffplayout_engine/ffplayout/output/stream.py", line 142, in output
    if ff_proc.encoder.poll() is None:
AttributeError: 'NoneType' object has no attribute 'poll'

Please suggest to me how to fix this issue I tried to find out the solution on google but it's not mentioned anywhere. So please help me out.

**Comment by jb-alvarado** [comment]
Hello, this is a very old and closed issue. Please create next time a new one, with the template.

Anyway, there was a error in the script, which is fixed now.
