### ISSUE TITLE
Logic of reading from folder and pushing to rtmp

### ISSUE THREAD

**Issue by abellybeer** [ffplayout/ffplayout-engine#71]
Hi, I am trying to understand the logic you applied in your code. I saw your post on earlier stackoverflow discussion and you put this git repo for people to use.

Currently I am running your code on windows and making it read from a folder of mine I upload files constantly and I need them to be pushed to a rmtp server as they are available.

I upload files in incremented order starting from 0 and so on. Your code does transcoding and it includes a logo on top-right of screen.

I wonder if you would could explain me what is your logic with python to detect new files and making ffmpeg push it to rtmp server without closing the connecting.

I know I have the source code but the more deep understanding I have the better is for me to write my own code.

By the way, you wrote an excellent tool!

Thanks in advance.

**Comment by jb-alvarado** [comment]
Hi,
the way of constantly stream I have described a bit in the [wiki](https://github.com/ffplayout/ffplayout-engine/wiki). I just create a pipe between two ffmpeg instances. One is always running and stream the input over rtmp, the other prepare all files to the same format. It is important to use **mpegts** as format for the pipe, because every packet have its sync information. With other formats you will have sync problems between audio and video.

For the folder reading I use the **watchdog** module to monitor the folder. When it register a change, the new file will be added to the list, or remove.
