### ISSUE TITLE
Play random files from folder

### ISSUE THREAD

**Issue by peppi001** [ffplayout/ffplayout-engine#81]
Hello!

I've got a problem.

The media folder I have 4 videos to test.
I set to play files from folder.
I set shuffle mode to True.

But my problem is: the videos not played randomly.
It plays the same order.

Example:
The random file order is 2,4,1,3. And this order repeat forever. ( 2,4,1,3,2,4,1,3,2,4,1,3....)
Is it normally or a bug?

I want to play random files with infinite loop from a folder, but this mode is not good for that.

Thanks.

**Comment by jb-alvarado** [comment]
At the moment this is the normal behaviour. I understand your issue and I can change the random function.

Personally I don't like many of the random functions. Python has also a **random.choice** function which you can use for infinite loops, but the problem is, that you have no control over it, it can happen that some clips played many times, also repeating one clip 2 times, and other clips don't play at all. A almost similar problem I have, when I randomize the list ones and when it starts again, I randomize the list again. Here it also can happen, that the last clip from the last list becomes now the first clip in the new list, so this one will play twice.

**Comment by jb-alvarado** [comment]
A note for me: **MediaStore()** class should work different in the add/remove function. It must sort or randomize depending on config.

**Comment by peppi001** [comment]
Thanks and wait for update :)
