### ISSUE TITLE
Ingest of Live

### ISSUE THREAD

**Issue by jengajenga** [ffplayout/ffplayout-engine#96]
@jb-alvarado hi

After our long discussion, the playout seems to be stable. HOwever I received a request from my test user.

Is it possible to take a live feed and put it into the playout and play? Right now we can only upload and play. But I would like a situation where the a live feed can be ingested to and play directly from there.

It could be an rtmp or a hls/m3u8 file.

What do you say?

Thanks.

**Comment by jb-alvarado** [comment]
Hello,

the ffplayout-engine doesn't support live input. But with the combination with SRS hls and ffplayout-api it is possible to do this, at least in theories.

The idea is that there are two different streams, tv and event. As soon as an event stream comes in, ffplayout-api kicks the tv stream so that the event stream can write to the same hls playlist.

When the event stream stops, the API registers that too and starts the tv stream again.

Is not widely tested, and at the moment I cannot give support for that. [Here](https://github.com/ffplayout/ffplayout-docker/blob/master/examples/tv-event.conf) you would found a example srs config for that.

rtmp address should be:

> rtmp://[ip]/live?vhost=tv_stream&key=[key]/tv
> rtmp://[ip]/live?vhost=event_stream&key=[key]/event

Key can be configure [here](https://github.com/ffplayout/ffplayout-api/blob/6621f36b37737a5d6ce074a4418ca813b3baed95/ffplayout/ffplayout/settings/common.py#L165).

**Comment by jengajenga** [comment]
> Hello,
> 
> the ffplayout-engine doesn't support live input. But with the combination with SRS hls and ffplayout-api it is possible to do this, at least in theories.
> 
> The idea is that there are two different streams, tv and event. As soon as an event stream comes in, ffplayout-api kicks the tv stream so that the event stream can write to the same hls playlist.
> 
> When the event stream stops, the API registers that too and starts the tv stream again.
> 
> Is not widely tested, and at the moment I cannot give support for that. [Here](https://github.com/ffplayout/ffplayout-docker/blob/master/examples/tv-event.conf) you would found a example srs config for that.
> 
> rtmp address should be:
> 
> > rtmp://[ip]/live?vhost=tv_stream&key=[key]/tv
> > rtmp://[ip]/live?vhost=event_stream&key=[key]/event
> 
> Key can be configure [here](https://github.com/ffplayout/ffplayout-api/blob/6621f36b37737a5d6ce074a4418ca813b3baed95/ffplayout/ffplayout/settings/common.py#L165).

Thanks. I will look into this. I hope it is a simple process.

**Comment by edwoodza** [comment]
any luck with supporting live in natively in the project via GUI?
Not had much luck with the options above.

ideally add stream as media. and then the engine sees streaming and does not look for the stuff it does for files.
tried adding hls as media file but when it prechecks media it fails test and does not work.
